Month 7/step 2
nmsosin/react-burger pull request #1
Opened 2023-01-16 08:20 UTC by nmsosin

Add API data request, general markup, modal open/close feature and prop-types check

2023-01-16 09:13 UTC, andryxxa93 requested changes
Проделана большая работа! Вы хорошо разобрались с функциональными компонентами, правильно используете useEffect и PropTypes.

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Не у всех компонентов есть типизация пропсов.
- Добавьте проверку успешности запроса
- Всю логику из `ModalOverlay` необходимо вынести в `Modal`
- Модалка работает некорректно. После открытия/закрытия модалка больше не открывается.

https://user-images.githubusercontent.com/60173362/212640554-836d5176-2970-4fbc-8589-b1f788be0dff.mov
- Не работает закрытие модалки нажатием на подложку.

Более подробно описание проблемы смотрите комментарии в pull request.


В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2023-01-16 09:13 UTC, andryxxa93 commented on src/components/App/App.jsx
> +      const res = await fetch(dataUrl);
**Можно лучше**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции

Например:

```
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}

```

и разместить их в отдельном файле  `utils/burger-api.js`, а не описывать запросы в самом компоненте

2023-01-16 09:13 UTC, andryxxa93 commented on src/components/App/App.jsx
> +      const result = await res.json();
**Надо исправить**
Добавьте проверку ответа сервера - res.ok:

Например:

```
.then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
```

иначе сейчас, если сервер ответи не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение

[https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)

[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

`fetch(someUrl).then(checkReponse)`

2023-01-16 09:13 UTC, andryxxa93 commented on src/components/App/App.jsx
> +      console.log(`Ой! При запросе данных произошла ошибка: ${err}`);
**Можно улучшить**
Console.log нужен только для процесса разработки, перед сдачей проекта его нужно удалять, иначе она будет загружать консоль ненужной, а возможно и приватной информацией. А ошибку лучше записывать в state и показывать пользователю, чтобы он понимал, что происходит.

2023-01-16 09:13 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.jsx
> +const BurgerConstructor = (props) => {
**Можно улучшить**
Здесь и в коде других компонентов, лучше не писать каждый раз `props`, а использовать деструктуризацию, достав все необходимые данные из пропсов один раз. Это сделает код более понятным. https://learn.javascript.ru/destructuring#destrukturizatsiya-obekta

2023-01-16 09:13 UTC, andryxxa93 commented on src/components/modal-overlay/modal-overlay.jsx
> +const ModalOverlay = (props) => {
**Надо исправить**

у `ModalOverlay` не должно быть `children` ни логики, это просто компонент подложки а не контейнер

2023-01-16 09:13 UTC, andryxxa93 commented on src/components/modal/modal.jsx
> +  const {onClose} = props;
**Необходимо исправить**
Нет типизации функции `onClose `

2023-01-17 17:59 UTC, closed without merging

2023-01-17 18:00 UTC, nmsosin commented
Hotfix done